services:
  - type: web
    name: primepark-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://primepark-backend.onrender.com
